format = "$directory$all"

[directory]
style = "blue"


[kubernetes]
disabled = false
format = '\([⎈](bold fg:33) [$cluster](fg:166):[$namespace](dimmed green)\) '

[aws]
disabled = true
force_display = true
style = 'yellow'

[python]
disabled = true

[battery]
disabled = true
