---
name: ci

on:
  workflow_dispatch: {}
  push:
    branches: [master]
  pull_request:
    branches: [master]
env:
  GC_PROJECT_ID: gankster-staging
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: "recursive"
      - name: echo
        run: echo "hello-world"
